"""Add password hash

Revision ID: 59cb897fc29a
Revises: dd77068a186a
Create Date: 2026-04-30 11:22:18.522303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "59cb897fc29a"
down_revision: Union[str, Sequence[str], None] = "dd77068a186a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_date",
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        existing_nullable=False,
        postgresql_using="published_date::date",
    )
    op.add_column(
        "users",
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.alter_column(
        "books",
        "published_date",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="published_date::varchar",
    )
    # ### end Alembic commands ###
